// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/constructs.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bar int32

const (
	Bar_BAR1 Bar = 0
	Bar_BAR2 Bar = 1
	Bar_BAR3 Bar = 2
)

var Bar_name = map[int32]string{
	0: "BAR1",
	1: "BAR2",
	2: "BAR3",
}

var Bar_value = map[string]int32{
	"BAR1": 0,
	"BAR2": 1,
	"BAR3": 2,
}

func (x Bar) String() string {
	return proto.EnumName(Bar_name, int32(x))
}

func (Bar) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{0}
}

type Ref_Foo_En int32

const (
	Ref_Foo_A0 Ref_Foo_En = 0
	Ref_Foo_A1 Ref_Foo_En = 1
)

var Ref_Foo_En_name = map[int32]string{
	0: "A0",
	1: "A1",
}

var Ref_Foo_En_value = map[string]int32{
	"A0": 0,
	"A1": 1,
}

func (x Ref_Foo_En) String() string {
	return proto.EnumName(Ref_Foo_En_name, int32(x))
}

func (Ref_Foo_En) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 1, 0}
}

type Ref_Foo_Bar_En int32

const (
	Ref_Foo_Bar_A0 Ref_Foo_Bar_En = 0
	Ref_Foo_Bar_A1 Ref_Foo_Bar_En = 1
)

var Ref_Foo_Bar_En_name = map[int32]string{
	0: "A0",
	1: "A1",
}

var Ref_Foo_Bar_En_value = map[string]int32{
	"A0": 0,
	"A1": 1,
}

func (x Ref_Foo_Bar_En) String() string {
	return proto.EnumName(Ref_Foo_Bar_En_name, int32(x))
}

func (Ref_Foo_Bar_En) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 1, 1, 0}
}

type Empty3 struct {
	I                    *Empty3_Int `protobuf:"bytes,1,opt,name=i,proto3" json:"i,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Empty3) Reset()         { *m = Empty3{} }
func (m *Empty3) String() string { return proto.CompactTextString(m) }
func (*Empty3) ProtoMessage()    {}
func (*Empty3) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{0}
}

func (m *Empty3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty3.Unmarshal(m, b)
}
func (m *Empty3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty3.Marshal(b, m, deterministic)
}
func (m *Empty3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty3.Merge(m, src)
}
func (m *Empty3) XXX_Size() int {
	return xxx_messageInfo_Empty3.Size(m)
}
func (m *Empty3) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty3.DiscardUnknown(m)
}

var xxx_messageInfo_Empty3 proto.InternalMessageInfo

func (m *Empty3) GetI() *Empty3_Int {
	if m != nil {
		return m.I
	}
	return nil
}

type Empty3_Int struct {
	E                    *Empty3  `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty3_Int) Reset()         { *m = Empty3_Int{} }
func (m *Empty3_Int) String() string { return proto.CompactTextString(m) }
func (*Empty3_Int) ProtoMessage()    {}
func (*Empty3_Int) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{0, 0}
}

func (m *Empty3_Int) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty3_Int.Unmarshal(m, b)
}
func (m *Empty3_Int) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty3_Int.Marshal(b, m, deterministic)
}
func (m *Empty3_Int) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty3_Int.Merge(m, src)
}
func (m *Empty3_Int) XXX_Size() int {
	return xxx_messageInfo_Empty3_Int.Size(m)
}
func (m *Empty3_Int) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty3_Int.DiscardUnknown(m)
}

var xxx_messageInfo_Empty3_Int proto.InternalMessageInfo

func (m *Empty3_Int) GetE() *Empty3 {
	if m != nil {
		return m.E
	}
	return nil
}

type Foo struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2               string   `protobuf:"bytes,2,opt,name=param2,proto3" json:"param2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{1}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

func (m *Foo) GetParam2() string {
	if m != nil {
		return m.Param2
	}
	return ""
}

type Foo_Foo2 struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo_Foo2) Reset()         { *m = Foo_Foo2{} }
func (m *Foo_Foo2) String() string { return proto.CompactTextString(m) }
func (*Foo_Foo2) ProtoMessage()    {}
func (*Foo_Foo2) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{1, 0}
}

func (m *Foo_Foo2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo_Foo2.Unmarshal(m, b)
}
func (m *Foo_Foo2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo_Foo2.Marshal(b, m, deterministic)
}
func (m *Foo_Foo2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo_Foo2.Merge(m, src)
}
func (m *Foo_Foo2) XXX_Size() int {
	return xxx_messageInfo_Foo_Foo2.Size(m)
}
func (m *Foo_Foo2) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo_Foo2.DiscardUnknown(m)
}

var xxx_messageInfo_Foo_Foo2 proto.InternalMessageInfo

func (m *Foo_Foo2) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type Baz struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Baz) Reset()         { *m = Baz{} }
func (m *Baz) String() string { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()    {}
func (*Baz) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{2}
}

func (m *Baz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Baz.Unmarshal(m, b)
}
func (m *Baz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Baz.Marshal(b, m, deterministic)
}
func (m *Baz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Baz.Merge(m, src)
}
func (m *Baz) XXX_Size() int {
	return xxx_messageInfo_Baz.Size(m)
}
func (m *Baz) XXX_DiscardUnknown() {
	xxx_messageInfo_Baz.DiscardUnknown(m)
}

var xxx_messageInfo_Baz proto.InternalMessageInfo

func (m *Baz) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type Scalars struct {
	Double               float64  `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float                float32  `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32                int32    `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64                int64    `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32               uint32   `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64               uint64   `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32               int32    `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64               int64    `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32              uint32   `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64              uint64   `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32             int32    `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64             int64    `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool                 bool     `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_              string   `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes                []byte   `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scalars) Reset()         { *m = Scalars{} }
func (m *Scalars) String() string { return proto.CompactTextString(m) }
func (*Scalars) ProtoMessage()    {}
func (*Scalars) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{3}
}

func (m *Scalars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scalars.Unmarshal(m, b)
}
func (m *Scalars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scalars.Marshal(b, m, deterministic)
}
func (m *Scalars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scalars.Merge(m, src)
}
func (m *Scalars) XXX_Size() int {
	return xxx_messageInfo_Scalars.Size(m)
}
func (m *Scalars) XXX_DiscardUnknown() {
	xxx_messageInfo_Scalars.DiscardUnknown(m)
}

var xxx_messageInfo_Scalars proto.InternalMessageInfo

func (m *Scalars) GetDouble() float64 {
	if m != nil {
		return m.Double
	}
	return 0
}

func (m *Scalars) GetFloat() float32 {
	if m != nil {
		return m.Float
	}
	return 0
}

func (m *Scalars) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *Scalars) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Scalars) GetUint32() uint32 {
	if m != nil {
		return m.Uint32
	}
	return 0
}

func (m *Scalars) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

func (m *Scalars) GetSint32() int32 {
	if m != nil {
		return m.Sint32
	}
	return 0
}

func (m *Scalars) GetSint64() int64 {
	if m != nil {
		return m.Sint64
	}
	return 0
}

func (m *Scalars) GetFixed32() uint32 {
	if m != nil {
		return m.Fixed32
	}
	return 0
}

func (m *Scalars) GetFixed64() uint64 {
	if m != nil {
		return m.Fixed64
	}
	return 0
}

func (m *Scalars) GetSfixed32() int32 {
	if m != nil {
		return m.Sfixed32
	}
	return 0
}

func (m *Scalars) GetSfixed64() int64 {
	if m != nil {
		return m.Sfixed64
	}
	return 0
}

func (m *Scalars) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Scalars) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Scalars) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type Repeated struct {
	Double               []float64 `protobuf:"fixed64,1,rep,packed,name=double,proto3" json:"double,omitempty"`
	Float                []float32 `protobuf:"fixed32,2,rep,packed,name=float,proto3" json:"float,omitempty"`
	Int32                []int32   `protobuf:"varint,3,rep,packed,name=int32,proto3" json:"int32,omitempty"`
	Int64                []int64   `protobuf:"varint,4,rep,packed,name=int64,proto3" json:"int64,omitempty"`
	Uint32               []uint32  `protobuf:"varint,5,rep,packed,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64               []uint64  `protobuf:"varint,6,rep,packed,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32               []int32   `protobuf:"zigzag32,7,rep,packed,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64               []int64   `protobuf:"zigzag64,8,rep,packed,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32              []uint32  `protobuf:"fixed32,9,rep,packed,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64              []uint64  `protobuf:"fixed64,10,rep,packed,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32             []int32   `protobuf:"fixed32,11,rep,packed,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64             []int64   `protobuf:"fixed64,12,rep,packed,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool                 []bool    `protobuf:"varint,13,rep,packed,name=bool,proto3" json:"bool,omitempty"`
	String_              []string  `protobuf:"bytes,14,rep,name=string,proto3" json:"string,omitempty"`
	Bytes                [][]byte  `protobuf:"bytes,15,rep,name=bytes,proto3" json:"bytes,omitempty"`
	Foo                  []*Foo    `protobuf:"bytes,16,rep,name=foo,proto3" json:"foo,omitempty"`
	Bar                  []Bar     `protobuf:"varint,17,rep,packed,name=bar,proto3,enum=pb.Bar" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Repeated) Reset()         { *m = Repeated{} }
func (m *Repeated) String() string { return proto.CompactTextString(m) }
func (*Repeated) ProtoMessage()    {}
func (*Repeated) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{4}
}

func (m *Repeated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repeated.Unmarshal(m, b)
}
func (m *Repeated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repeated.Marshal(b, m, deterministic)
}
func (m *Repeated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repeated.Merge(m, src)
}
func (m *Repeated) XXX_Size() int {
	return xxx_messageInfo_Repeated.Size(m)
}
func (m *Repeated) XXX_DiscardUnknown() {
	xxx_messageInfo_Repeated.DiscardUnknown(m)
}

var xxx_messageInfo_Repeated proto.InternalMessageInfo

func (m *Repeated) GetDouble() []float64 {
	if m != nil {
		return m.Double
	}
	return nil
}

func (m *Repeated) GetFloat() []float32 {
	if m != nil {
		return m.Float
	}
	return nil
}

func (m *Repeated) GetInt32() []int32 {
	if m != nil {
		return m.Int32
	}
	return nil
}

func (m *Repeated) GetInt64() []int64 {
	if m != nil {
		return m.Int64
	}
	return nil
}

func (m *Repeated) GetUint32() []uint32 {
	if m != nil {
		return m.Uint32
	}
	return nil
}

func (m *Repeated) GetUint64() []uint64 {
	if m != nil {
		return m.Uint64
	}
	return nil
}

func (m *Repeated) GetSint32() []int32 {
	if m != nil {
		return m.Sint32
	}
	return nil
}

func (m *Repeated) GetSint64() []int64 {
	if m != nil {
		return m.Sint64
	}
	return nil
}

func (m *Repeated) GetFixed32() []uint32 {
	if m != nil {
		return m.Fixed32
	}
	return nil
}

func (m *Repeated) GetFixed64() []uint64 {
	if m != nil {
		return m.Fixed64
	}
	return nil
}

func (m *Repeated) GetSfixed32() []int32 {
	if m != nil {
		return m.Sfixed32
	}
	return nil
}

func (m *Repeated) GetSfixed64() []int64 {
	if m != nil {
		return m.Sfixed64
	}
	return nil
}

func (m *Repeated) GetBool() []bool {
	if m != nil {
		return m.Bool
	}
	return nil
}

func (m *Repeated) GetString_() []string {
	if m != nil {
		return m.String_
	}
	return nil
}

func (m *Repeated) GetBytes() [][]byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Repeated) GetFoo() []*Foo {
	if m != nil {
		return m.Foo
	}
	return nil
}

func (m *Repeated) GetBar() []Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

type Maps struct {
	Int32Int32           map[int32]int32    `protobuf:"bytes,1,rep,name=int32_int32,json=int32Int32,proto3" json:"int32_int32,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Int64Int64           map[int64]int64    `protobuf:"bytes,2,rep,name=int64_int64,json=int64Int64,proto3" json:"int64_int64,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Uint32Uint32         map[uint32]uint32  `protobuf:"bytes,3,rep,name=uint32_uint32,json=uint32Uint32,proto3" json:"uint32_uint32,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Uint64Uint64         map[uint64]uint64  `protobuf:"bytes,4,rep,name=uint64_uint64,json=uint64Uint64,proto3" json:"uint64_uint64,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Sint32Sint32         map[int32]int32    `protobuf:"bytes,5,rep,name=sint32_sint32,json=sint32Sint32,proto3" json:"sint32_sint32,omitempty" protobuf_key:"zigzag32,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
	Sint64Sint64         map[int64]int64    `protobuf:"bytes,6,rep,name=sint64_sint64,json=sint64Sint64,proto3" json:"sint64_sint64,omitempty" protobuf_key:"zigzag64,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	Fixed32Fixed32       map[uint32]uint32  `protobuf:"bytes,7,rep,name=fixed32_fixed32,json=fixed32Fixed32,proto3" json:"fixed32_fixed32,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	Fixed64Fixed64       map[uint64]uint64  `protobuf:"bytes,8,rep,name=fixed64_fixed64,json=fixed64Fixed64,proto3" json:"fixed64_fixed64,omitempty" protobuf_key:"fixed64,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Sfixed32Sfixed32     map[int32]int32    `protobuf:"bytes,9,rep,name=sfixed32_sfixed32,json=sfixed32Sfixed32,proto3" json:"sfixed32_sfixed32,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	Sfixed64Sfixed64     map[int64]int64    `protobuf:"bytes,10,rep,name=sfixed64_sfixed64,json=sfixed64Sfixed64,proto3" json:"sfixed64_sfixed64,omitempty" protobuf_key:"fixed64,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	BoolBool             map[bool]bool      `protobuf:"bytes,11,rep,name=bool_bool,json=boolBool,proto3" json:"bool_bool,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	StringString         map[string]string  `protobuf:"bytes,12,rep,name=string_string,json=stringString,proto3" json:"string_string,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringBytes          map[string][]byte  `protobuf:"bytes,15,rep,name=string_bytes,json=stringBytes,proto3" json:"string_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringFloat          map[string]float32 `protobuf:"bytes,16,rep,name=string_float,json=stringFloat,proto3" json:"string_float,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	StringDouble         map[string]float64 `protobuf:"bytes,17,rep,name=string_double,json=stringDouble,proto3" json:"string_double,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	StringFoo            map[string]*Foo    `protobuf:"bytes,13,rep,name=string_foo,json=stringFoo,proto3" json:"string_foo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringBar            map[string]Bar     `protobuf:"bytes,14,rep,name=string_bar,json=stringBar,proto3" json:"string_bar,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=pb.Bar"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Maps) Reset()         { *m = Maps{} }
func (m *Maps) String() string { return proto.CompactTextString(m) }
func (*Maps) ProtoMessage()    {}
func (*Maps) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{5}
}

func (m *Maps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Maps.Unmarshal(m, b)
}
func (m *Maps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Maps.Marshal(b, m, deterministic)
}
func (m *Maps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Maps.Merge(m, src)
}
func (m *Maps) XXX_Size() int {
	return xxx_messageInfo_Maps.Size(m)
}
func (m *Maps) XXX_DiscardUnknown() {
	xxx_messageInfo_Maps.DiscardUnknown(m)
}

var xxx_messageInfo_Maps proto.InternalMessageInfo

func (m *Maps) GetInt32Int32() map[int32]int32 {
	if m != nil {
		return m.Int32Int32
	}
	return nil
}

func (m *Maps) GetInt64Int64() map[int64]int64 {
	if m != nil {
		return m.Int64Int64
	}
	return nil
}

func (m *Maps) GetUint32Uint32() map[uint32]uint32 {
	if m != nil {
		return m.Uint32Uint32
	}
	return nil
}

func (m *Maps) GetUint64Uint64() map[uint64]uint64 {
	if m != nil {
		return m.Uint64Uint64
	}
	return nil
}

func (m *Maps) GetSint32Sint32() map[int32]int32 {
	if m != nil {
		return m.Sint32Sint32
	}
	return nil
}

func (m *Maps) GetSint64Sint64() map[int64]int64 {
	if m != nil {
		return m.Sint64Sint64
	}
	return nil
}

func (m *Maps) GetFixed32Fixed32() map[uint32]uint32 {
	if m != nil {
		return m.Fixed32Fixed32
	}
	return nil
}

func (m *Maps) GetFixed64Fixed64() map[uint64]uint64 {
	if m != nil {
		return m.Fixed64Fixed64
	}
	return nil
}

func (m *Maps) GetSfixed32Sfixed32() map[int32]int32 {
	if m != nil {
		return m.Sfixed32Sfixed32
	}
	return nil
}

func (m *Maps) GetSfixed64Sfixed64() map[int64]int64 {
	if m != nil {
		return m.Sfixed64Sfixed64
	}
	return nil
}

func (m *Maps) GetBoolBool() map[bool]bool {
	if m != nil {
		return m.BoolBool
	}
	return nil
}

func (m *Maps) GetStringString() map[string]string {
	if m != nil {
		return m.StringString
	}
	return nil
}

func (m *Maps) GetStringBytes() map[string][]byte {
	if m != nil {
		return m.StringBytes
	}
	return nil
}

func (m *Maps) GetStringFloat() map[string]float32 {
	if m != nil {
		return m.StringFloat
	}
	return nil
}

func (m *Maps) GetStringDouble() map[string]float64 {
	if m != nil {
		return m.StringDouble
	}
	return nil
}

func (m *Maps) GetStringFoo() map[string]*Foo {
	if m != nil {
		return m.StringFoo
	}
	return nil
}

func (m *Maps) GetStringBar() map[string]Bar {
	if m != nil {
		return m.StringBar
	}
	return nil
}

type Any struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{6}
}

func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (m *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(m, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func (m *Any) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type EmptyRecursive struct {
	Nested1              *empty.Empty    `protobuf:"bytes,1,opt,name=nested1,proto3" json:"nested1,omitempty"`
	Empty                *EmptyRecursive `protobuf:"bytes,2,opt,name=empty,proto3" json:"empty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EmptyRecursive) Reset()         { *m = EmptyRecursive{} }
func (m *EmptyRecursive) String() string { return proto.CompactTextString(m) }
func (*EmptyRecursive) ProtoMessage()    {}
func (*EmptyRecursive) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{8}
}

func (m *EmptyRecursive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRecursive.Unmarshal(m, b)
}
func (m *EmptyRecursive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRecursive.Marshal(b, m, deterministic)
}
func (m *EmptyRecursive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRecursive.Merge(m, src)
}
func (m *EmptyRecursive) XXX_Size() int {
	return xxx_messageInfo_EmptyRecursive.Size(m)
}
func (m *EmptyRecursive) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRecursive.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRecursive proto.InternalMessageInfo

func (m *EmptyRecursive) GetNested1() *empty.Empty {
	if m != nil {
		return m.Nested1
	}
	return nil
}

func (m *EmptyRecursive) GetEmpty() *EmptyRecursive {
	if m != nil {
		return m.Empty
	}
	return nil
}

type EmptyNested struct {
	Nested1              *EmptyNested_EmptyNested1 `protobuf:"bytes,1,opt,name=nested1,proto3" json:"nested1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *EmptyNested) Reset()         { *m = EmptyNested{} }
func (m *EmptyNested) String() string { return proto.CompactTextString(m) }
func (*EmptyNested) ProtoMessage()    {}
func (*EmptyNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{9}
}

func (m *EmptyNested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyNested.Unmarshal(m, b)
}
func (m *EmptyNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyNested.Marshal(b, m, deterministic)
}
func (m *EmptyNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyNested.Merge(m, src)
}
func (m *EmptyNested) XXX_Size() int {
	return xxx_messageInfo_EmptyNested.Size(m)
}
func (m *EmptyNested) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyNested.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyNested proto.InternalMessageInfo

func (m *EmptyNested) GetNested1() *EmptyNested_EmptyNested1 {
	if m != nil {
		return m.Nested1
	}
	return nil
}

type EmptyNested_EmptyNested1 struct {
	Nested2              *EmptyNested_EmptyNested1_EmptyNested2 `protobuf:"bytes,1,opt,name=nested2,proto3" json:"nested2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *EmptyNested_EmptyNested1) Reset()         { *m = EmptyNested_EmptyNested1{} }
func (m *EmptyNested_EmptyNested1) String() string { return proto.CompactTextString(m) }
func (*EmptyNested_EmptyNested1) ProtoMessage()    {}
func (*EmptyNested_EmptyNested1) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{9, 0}
}

func (m *EmptyNested_EmptyNested1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyNested_EmptyNested1.Unmarshal(m, b)
}
func (m *EmptyNested_EmptyNested1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyNested_EmptyNested1.Marshal(b, m, deterministic)
}
func (m *EmptyNested_EmptyNested1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyNested_EmptyNested1.Merge(m, src)
}
func (m *EmptyNested_EmptyNested1) XXX_Size() int {
	return xxx_messageInfo_EmptyNested_EmptyNested1.Size(m)
}
func (m *EmptyNested_EmptyNested1) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyNested_EmptyNested1.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyNested_EmptyNested1 proto.InternalMessageInfo

func (m *EmptyNested_EmptyNested1) GetNested2() *EmptyNested_EmptyNested1_EmptyNested2 {
	if m != nil {
		return m.Nested2
	}
	return nil
}

type EmptyNested_EmptyNested1_EmptyNested2 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyNested_EmptyNested1_EmptyNested2) Reset()         { *m = EmptyNested_EmptyNested1_EmptyNested2{} }
func (m *EmptyNested_EmptyNested1_EmptyNested2) String() string { return proto.CompactTextString(m) }
func (*EmptyNested_EmptyNested1_EmptyNested2) ProtoMessage()    {}
func (*EmptyNested_EmptyNested1_EmptyNested2) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{9, 0, 0}
}

func (m *EmptyNested_EmptyNested1_EmptyNested2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyNested_EmptyNested1_EmptyNested2.Unmarshal(m, b)
}
func (m *EmptyNested_EmptyNested1_EmptyNested2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyNested_EmptyNested1_EmptyNested2.Marshal(b, m, deterministic)
}
func (m *EmptyNested_EmptyNested1_EmptyNested2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyNested_EmptyNested1_EmptyNested2.Merge(m, src)
}
func (m *EmptyNested_EmptyNested1_EmptyNested2) XXX_Size() int {
	return xxx_messageInfo_EmptyNested_EmptyNested1_EmptyNested2.Size(m)
}
func (m *EmptyNested_EmptyNested1_EmptyNested2) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyNested_EmptyNested1_EmptyNested2.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyNested_EmptyNested1_EmptyNested2 proto.InternalMessageInfo

type Timestamp struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{10}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Ref struct {
	Empty                *empty.Empty         `protobuf:"bytes,10,opt,name=empty,proto3" json:"empty,omitempty"`
	LocalTime2           *Timestamp           `protobuf:"bytes,12,opt,name=local_time2,json=localTime2,proto3" json:"local_time2,omitempty"`
	External             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=external,proto3" json:"external,omitempty"`
	LocalTime            *Timestamp           `protobuf:"bytes,11,opt,name=local_time,json=localTime,proto3" json:"local_time,omitempty"`
	File                 *Baz                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	FileMsg              *Foo                 `protobuf:"bytes,8,opt,name=file_msg,json=fileMsg,proto3" json:"file_msg,omitempty"`
	FileEnum             Bar                  `protobuf:"varint,9,opt,name=file_enum,json=fileEnum,proto3,enum=pb.Bar" json:"file_enum,omitempty"`
	Local                *Ref_Foo             `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	Foreign              *Foo_Foo2            `protobuf:"bytes,4,opt,name=foreign,proto3" json:"foreign,omitempty"`
	En1                  Ref_Foo_En           `protobuf:"varint,5,opt,name=en1,proto3,enum=pb.Ref_Foo_En" json:"en1,omitempty"`
	En2                  Ref_Foo_Bar_En       `protobuf:"varint,6,opt,name=en2,proto3,enum=pb.Ref_Foo_Bar_En" json:"en2,omitempty"`
	Gz                   *Ref_Foo_Baz_Gz      `protobuf:"bytes,7,opt,name=gz,proto3" json:"gz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Ref) Reset()         { *m = Ref{} }
func (m *Ref) String() string { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()    {}
func (*Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11}
}

func (m *Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref.Unmarshal(m, b)
}
func (m *Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref.Marshal(b, m, deterministic)
}
func (m *Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref.Merge(m, src)
}
func (m *Ref) XXX_Size() int {
	return xxx_messageInfo_Ref.Size(m)
}
func (m *Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Ref proto.InternalMessageInfo

func (m *Ref) GetEmpty() *empty.Empty {
	if m != nil {
		return m.Empty
	}
	return nil
}

func (m *Ref) GetLocalTime2() *Timestamp {
	if m != nil {
		return m.LocalTime2
	}
	return nil
}

func (m *Ref) GetExternal() *timestamp.Timestamp {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *Ref) GetLocalTime() *Timestamp {
	if m != nil {
		return m.LocalTime
	}
	return nil
}

func (m *Ref) GetFile() *Baz {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Ref) GetFileMsg() *Foo {
	if m != nil {
		return m.FileMsg
	}
	return nil
}

func (m *Ref) GetFileEnum() Bar {
	if m != nil {
		return m.FileEnum
	}
	return Bar_BAR1
}

func (m *Ref) GetLocal() *Ref_Foo {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *Ref) GetForeign() *Foo_Foo2 {
	if m != nil {
		return m.Foreign
	}
	return nil
}

func (m *Ref) GetEn1() Ref_Foo_En {
	if m != nil {
		return m.En1
	}
	return Ref_Foo_A0
}

func (m *Ref) GetEn2() Ref_Foo_Bar_En {
	if m != nil {
		return m.En2
	}
	return Ref_Foo_Bar_A0
}

func (m *Ref) GetGz() *Ref_Foo_Baz_Gz {
	if m != nil {
		return m.Gz
	}
	return nil
}

type Ref_Bar struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref_Bar) Reset()         { *m = Ref_Bar{} }
func (m *Ref_Bar) String() string { return proto.CompactTextString(m) }
func (*Ref_Bar) ProtoMessage()    {}
func (*Ref_Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 0}
}

func (m *Ref_Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref_Bar.Unmarshal(m, b)
}
func (m *Ref_Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref_Bar.Marshal(b, m, deterministic)
}
func (m *Ref_Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref_Bar.Merge(m, src)
}
func (m *Ref_Bar) XXX_Size() int {
	return xxx_messageInfo_Ref_Bar.Size(m)
}
func (m *Ref_Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Ref_Bar proto.InternalMessageInfo

func (m *Ref_Bar) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type Ref_Foo struct {
	Bar1                 *Ref_Foo_Bar         `protobuf:"bytes,1,opt,name=bar1,proto3" json:"bar1,omitempty"`
	LocalTime2           *Timestamp           `protobuf:"bytes,12,opt,name=local_time2,json=localTime2,proto3" json:"local_time2,omitempty"`
	ExternalTime1        *timestamp.Timestamp `protobuf:"bytes,13,opt,name=external_time1,json=externalTime1,proto3" json:"external_time1,omitempty"`
	Bar2                 *Ref_Bar             `protobuf:"bytes,2,opt,name=bar2,proto3" json:"bar2,omitempty"`
	En1                  Ref_Foo_En           `protobuf:"varint,3,opt,name=en1,proto3,enum=pb.Ref_Foo_En" json:"en1,omitempty"`
	En2                  Ref_Foo_Bar_En       `protobuf:"varint,4,opt,name=en2,proto3,enum=pb.Ref_Foo_Bar_En" json:"en2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Ref_Foo) Reset()         { *m = Ref_Foo{} }
func (m *Ref_Foo) String() string { return proto.CompactTextString(m) }
func (*Ref_Foo) ProtoMessage()    {}
func (*Ref_Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 1}
}

func (m *Ref_Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref_Foo.Unmarshal(m, b)
}
func (m *Ref_Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref_Foo.Marshal(b, m, deterministic)
}
func (m *Ref_Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref_Foo.Merge(m, src)
}
func (m *Ref_Foo) XXX_Size() int {
	return xxx_messageInfo_Ref_Foo.Size(m)
}
func (m *Ref_Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Ref_Foo proto.InternalMessageInfo

func (m *Ref_Foo) GetBar1() *Ref_Foo_Bar {
	if m != nil {
		return m.Bar1
	}
	return nil
}

func (m *Ref_Foo) GetLocalTime2() *Timestamp {
	if m != nil {
		return m.LocalTime2
	}
	return nil
}

func (m *Ref_Foo) GetExternalTime1() *timestamp.Timestamp {
	if m != nil {
		return m.ExternalTime1
	}
	return nil
}

func (m *Ref_Foo) GetBar2() *Ref_Bar {
	if m != nil {
		return m.Bar2
	}
	return nil
}

func (m *Ref_Foo) GetEn1() Ref_Foo_En {
	if m != nil {
		return m.En1
	}
	return Ref_Foo_A0
}

func (m *Ref_Foo) GetEn2() Ref_Foo_Bar_En {
	if m != nil {
		return m.En2
	}
	return Ref_Foo_Bar_A0
}

type Ref_Foo_Baz struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref_Foo_Baz) Reset()         { *m = Ref_Foo_Baz{} }
func (m *Ref_Foo_Baz) String() string { return proto.CompactTextString(m) }
func (*Ref_Foo_Baz) ProtoMessage()    {}
func (*Ref_Foo_Baz) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 1, 0}
}

func (m *Ref_Foo_Baz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref_Foo_Baz.Unmarshal(m, b)
}
func (m *Ref_Foo_Baz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref_Foo_Baz.Marshal(b, m, deterministic)
}
func (m *Ref_Foo_Baz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref_Foo_Baz.Merge(m, src)
}
func (m *Ref_Foo_Baz) XXX_Size() int {
	return xxx_messageInfo_Ref_Foo_Baz.Size(m)
}
func (m *Ref_Foo_Baz) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref_Foo_Baz.DiscardUnknown(m)
}

var xxx_messageInfo_Ref_Foo_Baz proto.InternalMessageInfo

type Ref_Foo_Baz_Gz struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref_Foo_Baz_Gz) Reset()         { *m = Ref_Foo_Baz_Gz{} }
func (m *Ref_Foo_Baz_Gz) String() string { return proto.CompactTextString(m) }
func (*Ref_Foo_Baz_Gz) ProtoMessage()    {}
func (*Ref_Foo_Baz_Gz) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 1, 0, 0}
}

func (m *Ref_Foo_Baz_Gz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref_Foo_Baz_Gz.Unmarshal(m, b)
}
func (m *Ref_Foo_Baz_Gz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref_Foo_Baz_Gz.Marshal(b, m, deterministic)
}
func (m *Ref_Foo_Baz_Gz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref_Foo_Baz_Gz.Merge(m, src)
}
func (m *Ref_Foo_Baz_Gz) XXX_Size() int {
	return xxx_messageInfo_Ref_Foo_Baz_Gz.Size(m)
}
func (m *Ref_Foo_Baz_Gz) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref_Foo_Baz_Gz.DiscardUnknown(m)
}

var xxx_messageInfo_Ref_Foo_Baz_Gz proto.InternalMessageInfo

func (m *Ref_Foo_Baz_Gz) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type Ref_Foo_Bar struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref_Foo_Bar) Reset()         { *m = Ref_Foo_Bar{} }
func (m *Ref_Foo_Bar) String() string { return proto.CompactTextString(m) }
func (*Ref_Foo_Bar) ProtoMessage()    {}
func (*Ref_Foo_Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{11, 1, 1}
}

func (m *Ref_Foo_Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref_Foo_Bar.Unmarshal(m, b)
}
func (m *Ref_Foo_Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref_Foo_Bar.Marshal(b, m, deterministic)
}
func (m *Ref_Foo_Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref_Foo_Bar.Merge(m, src)
}
func (m *Ref_Foo_Bar) XXX_Size() int {
	return xxx_messageInfo_Ref_Foo_Bar.Size(m)
}
func (m *Ref_Foo_Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref_Foo_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Ref_Foo_Bar proto.InternalMessageInfo

func (m *Ref_Foo_Bar) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type Oneof struct {
	Param1 string `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	// Types that are valid to be assigned to Oneof1:
	//	*Oneof_Param2
	//	*Oneof_Param3
	Oneof1 isOneof_Oneof1 `protobuf_oneof:"Oneof1"`
	// Types that are valid to be assigned to Oneof2:
	//	*Oneof_Param4
	//	*Oneof_Param5
	Oneof2 isOneof_Oneof2 `protobuf_oneof:"Oneof2"`
	// Types that are valid to be assigned to Oneof3:
	//	*Oneof_Param6
	Oneof3               isOneof_Oneof3 `protobuf_oneof:"Oneof3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Oneof) Reset()         { *m = Oneof{} }
func (m *Oneof) String() string { return proto.CompactTextString(m) }
func (*Oneof) ProtoMessage()    {}
func (*Oneof) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b26b5786a6c7dc9, []int{12}
}

func (m *Oneof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Oneof.Unmarshal(m, b)
}
func (m *Oneof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Oneof.Marshal(b, m, deterministic)
}
func (m *Oneof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Oneof.Merge(m, src)
}
func (m *Oneof) XXX_Size() int {
	return xxx_messageInfo_Oneof.Size(m)
}
func (m *Oneof) XXX_DiscardUnknown() {
	xxx_messageInfo_Oneof.DiscardUnknown(m)
}

var xxx_messageInfo_Oneof proto.InternalMessageInfo

func (m *Oneof) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

type isOneof_Oneof1 interface {
	isOneof_Oneof1()
}

type Oneof_Param2 struct {
	Param2 string `protobuf:"bytes,2,opt,name=param2,proto3,oneof"`
}

type Oneof_Param3 struct {
	Param3 string `protobuf:"bytes,3,opt,name=param3,proto3,oneof"`
}

func (*Oneof_Param2) isOneof_Oneof1() {}

func (*Oneof_Param3) isOneof_Oneof1() {}

func (m *Oneof) GetOneof1() isOneof_Oneof1 {
	if m != nil {
		return m.Oneof1
	}
	return nil
}

func (m *Oneof) GetParam2() string {
	if x, ok := m.GetOneof1().(*Oneof_Param2); ok {
		return x.Param2
	}
	return ""
}

func (m *Oneof) GetParam3() string {
	if x, ok := m.GetOneof1().(*Oneof_Param3); ok {
		return x.Param3
	}
	return ""
}

type isOneof_Oneof2 interface {
	isOneof_Oneof2()
}

type Oneof_Param4 struct {
	Param4 string `protobuf:"bytes,4,opt,name=param4,proto3,oneof"`
}

type Oneof_Param5 struct {
	Param5 string `protobuf:"bytes,5,opt,name=param5,proto3,oneof"`
}

func (*Oneof_Param4) isOneof_Oneof2() {}

func (*Oneof_Param5) isOneof_Oneof2() {}

func (m *Oneof) GetOneof2() isOneof_Oneof2 {
	if m != nil {
		return m.Oneof2
	}
	return nil
}

func (m *Oneof) GetParam4() string {
	if x, ok := m.GetOneof2().(*Oneof_Param4); ok {
		return x.Param4
	}
	return ""
}

func (m *Oneof) GetParam5() string {
	if x, ok := m.GetOneof2().(*Oneof_Param5); ok {
		return x.Param5
	}
	return ""
}

type isOneof_Oneof3 interface {
	isOneof_Oneof3()
}

type Oneof_Param6 struct {
	Param6 string `protobuf:"bytes,6,opt,name=param6,proto3,oneof"`
}

func (*Oneof_Param6) isOneof_Oneof3() {}

func (m *Oneof) GetOneof3() isOneof_Oneof3 {
	if m != nil {
		return m.Oneof3
	}
	return nil
}

func (m *Oneof) GetParam6() string {
	if x, ok := m.GetOneof3().(*Oneof_Param6); ok {
		return x.Param6
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Oneof) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Oneof_Param2)(nil),
		(*Oneof_Param3)(nil),
		(*Oneof_Param4)(nil),
		(*Oneof_Param5)(nil),
		(*Oneof_Param6)(nil),
	}
}

func init() {
	proto.RegisterEnum("pb.Bar", Bar_name, Bar_value)
	proto.RegisterEnum("pb.Ref_Foo_En", Ref_Foo_En_name, Ref_Foo_En_value)
	proto.RegisterEnum("pb.Ref_Foo_Bar_En", Ref_Foo_Bar_En_name, Ref_Foo_Bar_En_value)
	proto.RegisterType((*Empty3)(nil), "pb.Empty3")
	proto.RegisterType((*Empty3_Int)(nil), "pb.Empty3.Int")
	proto.RegisterType((*Foo)(nil), "pb.Foo")
	proto.RegisterType((*Foo_Foo2)(nil), "pb.Foo.Foo2")
	proto.RegisterType((*Baz)(nil), "pb.Baz")
	proto.RegisterType((*Scalars)(nil), "pb.Scalars")
	proto.RegisterType((*Repeated)(nil), "pb.Repeated")
	proto.RegisterType((*Maps)(nil), "pb.Maps")
	proto.RegisterMapType((map[bool]bool)(nil), "pb.Maps.BoolBoolEntry")
	proto.RegisterMapType((map[uint32]uint32)(nil), "pb.Maps.Fixed32Fixed32Entry")
	proto.RegisterMapType((map[uint64]uint64)(nil), "pb.Maps.Fixed64Fixed64Entry")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.Maps.Int32Int32Entry")
	proto.RegisterMapType((map[int64]int64)(nil), "pb.Maps.Int64Int64Entry")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.Maps.Sfixed32Sfixed32Entry")
	proto.RegisterMapType((map[int64]int64)(nil), "pb.Maps.Sfixed64Sfixed64Entry")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.Maps.Sint32Sint32Entry")
	proto.RegisterMapType((map[int64]int64)(nil), "pb.Maps.Sint64Sint64Entry")
	proto.RegisterMapType((map[string]Bar)(nil), "pb.Maps.StringBarEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.Maps.StringBytesEntry")
	proto.RegisterMapType((map[string]float64)(nil), "pb.Maps.StringDoubleEntry")
	proto.RegisterMapType((map[string]float32)(nil), "pb.Maps.StringFloatEntry")
	proto.RegisterMapType((map[string]*Foo)(nil), "pb.Maps.StringFooEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.Maps.StringStringEntry")
	proto.RegisterMapType((map[uint32]uint32)(nil), "pb.Maps.Uint32Uint32Entry")
	proto.RegisterMapType((map[uint64]uint64)(nil), "pb.Maps.Uint64Uint64Entry")
	proto.RegisterType((*Any)(nil), "pb.Any")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*EmptyRecursive)(nil), "pb.EmptyRecursive")
	proto.RegisterType((*EmptyNested)(nil), "pb.EmptyNested")
	proto.RegisterType((*EmptyNested_EmptyNested1)(nil), "pb.EmptyNested.EmptyNested1")
	proto.RegisterType((*EmptyNested_EmptyNested1_EmptyNested2)(nil), "pb.EmptyNested.EmptyNested1.EmptyNested2")
	proto.RegisterType((*Timestamp)(nil), "pb.Timestamp")
	proto.RegisterType((*Ref)(nil), "pb.Ref")
	proto.RegisterType((*Ref_Bar)(nil), "pb.Ref.Bar")
	proto.RegisterType((*Ref_Foo)(nil), "pb.Ref.Foo")
	proto.RegisterType((*Ref_Foo_Baz)(nil), "pb.Ref.Foo.Baz")
	proto.RegisterType((*Ref_Foo_Baz_Gz)(nil), "pb.Ref.Foo.Baz.Gz")
	proto.RegisterType((*Ref_Foo_Bar)(nil), "pb.Ref.Foo.Bar")
	proto.RegisterType((*Oneof)(nil), "pb.Oneof")
}

func init() { proto.RegisterFile("example/constructs.proto", fileDescriptor_3b26b5786a6c7dc9) }

var fileDescriptor_3b26b5786a6c7dc9 = []byte{
	// 1737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0x5b, 0x93, 0xdb, 0x48,
	0x15, 0x8e, 0x24, 0x5f, 0x8f, 0x66, 0x7c, 0x69, 0x42, 0x50, 0x94, 0x6c, 0xa2, 0x75, 0x02, 0x08,
	0xd8, 0xf5, 0xac, 0x65, 0xaf, 0x0a, 0x58, 0x60, 0x6b, 0x1c, 0x66, 0x92, 0x14, 0xb5, 0x50, 0xd5,
	0xc3, 0x16, 0x55, 0xbc, 0xa8, 0x64, 0x8f, 0xec, 0x75, 0x21, 0x4b, 0x46, 0x92, 0x53, 0x99, 0xf9,
	0x45, 0xd4, 0xfe, 0x09, 0x7e, 0x13, 0x2f, 0xbc, 0x51, 0x50, 0x7d, 0x93, 0xda, 0x9a, 0xf6, 0x4c,
	0xf1, 0x30, 0x56, 0x9f, 0xcb, 0xf7, 0x75, 0xeb, 0xf4, 0xe9, 0x33, 0x3a, 0x0d, 0x56, 0xf4, 0x31,
	0xdc, 0xee, 0xe2, 0xe8, 0x6c, 0x99, 0x26, 0x79, 0x91, 0xed, 0x97, 0x45, 0x3e, 0xde, 0x65, 0x69,
	0x91, 0x22, 0x7d, 0xb7, 0xb0, 0x9f, 0xae, 0xd3, 0x74, 0x1d, 0x47, 0x67, 0x54, 0xb3, 0xd8, 0xaf,
	0xce, 0xc2, 0xe4, 0x86, 0x99, 0xed, 0x67, 0x75, 0x53, 0xb4, 0xdd, 0x15, 0xc2, 0xf8, 0xb2, 0x6e,
	0x2c, 0x36, 0xdb, 0x28, 0x2f, 0xc2, 0xed, 0x8e, 0x39, 0x8c, 0xde, 0x42, 0xeb, 0x82, 0xf8, 0x4f,
	0xd1, 0x73, 0xd0, 0x36, 0x96, 0xe6, 0x68, 0xae, 0xe9, 0xf5, 0xc6, 0xbb, 0xc5, 0x98, 0xa9, 0xc7,
	0xef, 0x93, 0x02, 0x6b, 0x1b, 0xfb, 0x25, 0x18, 0xef, 0x93, 0x02, 0x59, 0xa0, 0x45, 0xdc, 0x09,
	0x2a, 0x27, 0xac, 0x45, 0xa3, 0x6f, 0xc1, 0xb8, 0x4c, 0x53, 0xf4, 0x04, 0x5a, 0xbb, 0x30, 0x0b,
	0xb7, 0x13, 0xea, 0xd5, 0xc5, 0x5c, 0x2a, 0xf5, 0x9e, 0xa5, 0x4b, 0x7a, 0xcf, 0x7e, 0x01, 0x8d,
	0xcb, 0x34, 0xf5, 0x8e, 0xe1, 0x46, 0x9f, 0x80, 0x31, 0x0f, 0x6f, 0x8f, 0x9a, 0xff, 0xa5, 0x43,
	0xfb, 0x6a, 0x19, 0xc6, 0x61, 0x96, 0x13, 0x9f, 0xeb, 0x74, 0xbf, 0x88, 0xd9, 0x02, 0x35, 0xcc,
	0x25, 0xf4, 0x18, 0x9a, 0xab, 0x38, 0x0d, 0x0b, 0x3a, 0xb3, 0x8e, 0x99, 0x40, 0xb4, 0x9b, 0xa4,
	0x98, 0x7a, 0x96, 0xe1, 0x68, 0x6e, 0x13, 0x33, 0x81, 0x6b, 0xfd, 0x99, 0xd5, 0x70, 0x34, 0xd7,
	0xc0, 0x4c, 0x20, 0xcc, 0x7b, 0xe6, 0xdc, 0x74, 0x34, 0xf7, 0x14, 0x73, 0x49, 0xe8, 0xfd, 0x99,
	0xd5, 0x72, 0x34, 0xb7, 0x81, 0xb9, 0x44, 0xf4, 0x39, 0xf3, 0x6f, 0x3b, 0x9a, 0x3b, 0xc4, 0x5c,
	0x12, 0x7a, 0x7f, 0x66, 0x75, 0x1c, 0xcd, 0x45, 0x98, 0x4b, 0xc8, 0x82, 0xf6, 0x6a, 0xf3, 0x31,
	0xba, 0x9e, 0x7a, 0x56, 0xd7, 0xd1, 0xdc, 0x36, 0x16, 0x62, 0x69, 0xf1, 0x67, 0x16, 0x38, 0x9a,
	0xdb, 0xc2, 0x42, 0x44, 0x36, 0x74, 0x72, 0x01, 0x32, 0x1d, 0xcd, 0xed, 0xe3, 0x52, 0xae, 0x6c,
	0xfe, 0xcc, 0x3a, 0x71, 0x34, 0x77, 0x80, 0x4b, 0x19, 0x21, 0x68, 0x2c, 0xd2, 0x34, 0xb6, 0x4e,
	0x1d, 0xcd, 0xed, 0x60, 0x3a, 0xa6, 0xeb, 0x2a, 0xb2, 0x4d, 0xb2, 0xb6, 0x7a, 0x2c, 0xba, 0x4c,
	0x22, 0xd1, 0x58, 0xdc, 0x14, 0x51, 0x6e, 0xf5, 0x1d, 0xcd, 0x3d, 0xc1, 0x4c, 0x18, 0xfd, 0xc3,
	0x80, 0x0e, 0x8e, 0x76, 0x51, 0x58, 0x44, 0xd7, 0x07, 0x41, 0x37, 0xd4, 0x41, 0x37, 0x94, 0x41,
	0x37, 0x94, 0x41, 0x37, 0xd4, 0x41, 0x37, 0x8e, 0x04, 0xdd, 0x38, 0x12, 0x74, 0xe3, 0x48, 0xd0,
	0x8d, 0x63, 0x41, 0x37, 0x8e, 0x06, 0xdd, 0x38, 0x1e, 0x74, 0xe3, 0x9e, 0xa0, 0x1b, 0x47, 0x82,
	0x6e, 0x28, 0x83, 0x6e, 0xa8, 0x83, 0x6e, 0x94, 0x41, 0x47, 0x4f, 0xc1, 0x58, 0xa5, 0xa9, 0x35,
	0x70, 0x0c, 0xd7, 0xf4, 0xda, 0xe4, 0xe8, 0x5d, 0xa6, 0x29, 0x26, 0x3a, 0x62, 0x5a, 0x84, 0x99,
	0x35, 0x74, 0x0c, 0xb7, 0xc7, 0x4c, 0xf3, 0x30, 0xc3, 0x44, 0x37, 0xfa, 0x7e, 0x08, 0x8d, 0x6f,
	0xc2, 0x5d, 0x8e, 0x7e, 0x05, 0x26, 0x8d, 0x46, 0xc0, 0x22, 0xa4, 0x51, 0x1a, 0x8b, 0xf8, 0x12,
	0x33, 0x39, 0xe4, 0x53, 0x8f, 0xfe, 0x5c, 0x24, 0x45, 0x76, 0x83, 0x61, 0x53, 0x2a, 0x38, 0xd4,
	0x9f, 0x05, 0x2c, 0x88, 0xfa, 0x5d, 0xa8, 0x3f, 0xa3, 0x3f, 0x15, 0x94, 0x2b, 0xd0, 0xd7, 0x70,
	0xca, 0x36, 0x2d, 0xd8, 0x57, 0xdb, 0x6e, 0x7a, 0x76, 0x09, 0xfe, 0x96, 0xaa, 0xd9, 0x2f, 0x83,
	0x9f, 0xec, 0x25, 0x95, 0x20, 0xf0, 0x67, 0xc1, 0xbe, 0xca, 0x90, 0x3a, 0x81, 0x3f, 0x63, 0xbf,
	0x12, 0x81, 0x50, 0x11, 0x02, 0x96, 0x06, 0x41, 0x5e, 0xe5, 0x92, 0x4c, 0x70, 0x45, 0xd5, 0x57,
	0xf2, 0x0a, 0x72, 0x49, 0x25, 0x08, 0xfc, 0x59, 0x90, 0x57, 0x49, 0x57, 0x27, 0xf0, 0x67, 0x57,
	0xf2, 0x0a, 0x72, 0x49, 0x85, 0x2e, 0xa0, 0xcf, 0x33, 0x24, 0x10, 0x99, 0xd3, 0xa6, 0x14, 0xcf,
	0x4b, 0x8a, 0x4b, 0xa6, 0xe7, 0x0f, 0x46, 0xd2, 0x5b, 0x1d, 0x28, 0x4b, 0x1a, 0x7f, 0x16, 0x88,
	0x24, 0xeb, 0xa8, 0x68, 0xfc, 0x19, 0x7f, 0xc8, 0x34, 0xa5, 0x12, 0xfd, 0x01, 0x86, 0x22, 0x61,
	0x83, 0x5c, 0x4e, 0x7f, 0xd3, 0x7b, 0x51, 0xbd, 0x12, 0x37, 0x88, 0x27, 0xa3, 0x1a, 0xe4, 0x35,
	0x75, 0x45, 0x46, 0xa2, 0x23, 0x9f, 0x98, 0xbb, 0x64, 0xfe, 0x4c, 0x3c, 0x0f, 0xc8, 0x2a, 0x35,
	0x9a, 0x42, 0x97, 0x1c, 0x8b, 0x80, 0x9e, 0x13, 0x93, 0x92, 0x3c, 0x29, 0x49, 0xe6, 0x69, 0x1a,
	0x93, 0x3f, 0x06, 0xee, 0x2c, 0xb8, 0x48, 0x77, 0x87, 0x9e, 0x9a, 0x80, 0x1f, 0xa5, 0x93, 0xfa,
	0xee, 0x50, 0x35, 0xfb, 0x15, 0xbb, 0x23, 0xa9, 0xd0, 0x6f, 0x80, 0xcb, 0x41, 0x75, 0xe6, 0x4c,
	0xef, 0x69, 0x0d, 0x3f, 0x27, 0x36, 0x06, 0x37, 0xf3, 0x4a, 0x23, 0xa1, 0x59, 0xad, 0x1b, 0x28,
	0xd1, 0x97, 0xc4, 0x76, 0x80, 0xa6, 0x1a, 0x69, 0xf1, 0xbc, 0x82, 0x0e, 0x95, 0x8b, 0xff, 0x3d,
	0x35, 0x1e, 0x2c, 0x9e, 0xa9, 0x90, 0x0f, 0x20, 0xa6, 0x4f, 0x53, 0x5a, 0x5b, 0x4c, 0xef, 0x47,
	0xf5, 0xc9, 0xd3, 0x94, 0x41, 0xbb, 0xb9, 0x90, 0x25, 0x1c, 0xa9, 0x1b, 0x3d, 0x25, 0x6e, 0x1e,
	0x66, 0x07, 0xb8, 0x79, 0x98, 0xd9, 0xbf, 0x85, 0x7e, 0xad, 0x50, 0xa0, 0x01, 0x18, 0x7f, 0x8b,
	0x6e, 0xe8, 0x3f, 0xdc, 0x26, 0x26, 0x43, 0x52, 0xbe, 0x3e, 0x84, 0xf1, 0x3e, 0xa2, 0xff, 0x6d,
	0x9b, 0x98, 0x09, 0xbf, 0xd6, 0x7f, 0xa9, 0x71, 0xb8, 0x5c, 0x2c, 0x64, 0xb8, 0xa1, 0x80, 0x1b,
	0x32, 0xfc, 0x6b, 0x18, 0xde, 0x29, 0x17, 0x32, 0xc1, 0xa9, 0x82, 0xe0, 0x54, 0x41, 0x70, 0x50,
	0x2e, 0x64, 0x82, 0x86, 0x82, 0xa0, 0x51, 0x23, 0xb8, 0x53, 0x2e, 0x64, 0x82, 0xa1, 0x82, 0x60,
	0xa8, 0x20, 0x38, 0x28, 0x17, 0x32, 0x01, 0x52, 0x10, 0x20, 0x99, 0xe0, 0x1c, 0x7e, 0xa0, 0x28,
	0x16, 0x32, 0x45, 0x5b, 0x41, 0xd1, 0x56, 0x51, 0x1c, 0x16, 0x0a, 0x99, 0xa2, 0xa5, 0xa0, 0x68,
	0xc9, 0x14, 0x6f, 0xe0, 0x87, 0xca, 0x12, 0x21, 0x93, 0xf4, 0x15, 0x24, 0x7d, 0x25, 0x49, 0xad,
	0x34, 0xc8, 0x24, 0x03, 0x05, 0xc9, 0x40, 0x26, 0xf9, 0x0a, 0x4e, 0x0f, 0x4a, 0x83, 0x0c, 0xee,
	0x28, 0xc0, 0x9d, 0xfa, 0x6e, 0xd4, 0xcb, 0x83, 0x4c, 0xd0, 0x55, 0x10, 0x74, 0x65, 0x82, 0xdf,
	0xc1, 0xa0, 0x5e, 0x1f, 0x1e, 0xc2, 0x9f, 0x28, 0xf1, 0x55, 0x85, 0x78, 0x08, 0xaf, 0x2b, 0x5f,
	0x40, 0x2a, 0x11, 0x0f, 0x11, 0x68, 0x32, 0xc1, 0x05, 0xf4, 0x0e, 0xab, 0x84, 0x02, 0xfd, 0x89,
	0x8c, 0x96, 0x3e, 0x3d, 0x54, 0x34, 0xa2, 0x68, 0x3c, 0x44, 0x23, 0x7d, 0xa6, 0x54, 0x34, 0xe4,
	0x53, 0xff, 0x3c, 0xb9, 0x39, 0xfa, 0xa9, 0xdf, 0x86, 0x26, 0xed, 0x36, 0x46, 0x31, 0xf4, 0xe8,
	0x00, 0x47, 0xcb, 0x7d, 0x96, 0x6f, 0x3e, 0x44, 0xe8, 0x0b, 0x68, 0x27, 0x51, 0x5e, 0x44, 0xd7,
	0x13, 0xde, 0x9b, 0x3c, 0x19, 0xb3, 0xbe, 0x67, 0x2c, 0xfa, 0x1e, 0xd6, 0xa8, 0x60, 0xe1, 0x86,
	0x5c, 0x68, 0xd2, 0x36, 0x89, 0xbf, 0x15, 0x2a, 0x7b, 0x99, 0x92, 0x14, 0x33, 0x87, 0xd1, 0xf7,
	0x1a, 0x98, 0xd4, 0xf2, 0x47, 0x0a, 0x45, 0x7e, 0x7d, 0xae, 0xe7, 0x25, 0x96, 0x79, 0xc8, 0xe3,
	0x49, 0x39, 0xa3, 0xbd, 0x84, 0x13, 0xd9, 0x80, 0xde, 0x08, 0x1e, 0x8f, 0xf3, 0xfc, 0xec, 0x3e,
	0x1e, 0x59, 0xf0, 0x04, 0xa9, 0x67, 0xf7, 0x0e, 0x48, 0xbd, 0xd1, 0x4b, 0xe8, 0xfe, 0x59, 0x34,
	0x78, 0xe4, 0xa3, 0x93, 0x74, 0x7b, 0x3c, 0x8c, 0x74, 0x3c, 0xfa, 0x6f, 0x0b, 0x0c, 0x1c, 0xad,
	0xd0, 0x67, 0xe2, 0xfd, 0xe1, 0xde, 0x78, 0x31, 0x27, 0x34, 0x06, 0x33, 0x4e, 0x97, 0x61, 0x1c,
	0x10, 0x0e, 0x8f, 0xb6, 0x14, 0xa6, 0x77, 0x4a, 0xd6, 0x5b, 0xce, 0x86, 0x81, 0x7a, 0x10, 0xd9,
	0x43, 0x3e, 0x74, 0xa2, 0x8f, 0x45, 0x94, 0x25, 0x61, 0xcc, 0x5f, 0xce, 0xbe, 0x33, 0x41, 0x85,
	0x2c, 0x7d, 0xd1, 0x67, 0x00, 0xd5, 0x3c, 0xb4, 0xab, 0xb9, 0x33, 0x4d, 0xb7, 0x9c, 0x06, 0x3d,
	0x83, 0xc6, 0x6a, 0x13, 0x1f, 0x24, 0xe6, 0x3c, 0xbc, 0xc5, 0x54, 0x89, 0x46, 0xd0, 0x21, 0xcf,
	0x60, 0x9b, 0xaf, 0x69, 0xb3, 0x25, 0x65, 0x6e, 0x9b, 0x18, 0xbe, 0xc9, 0xd7, 0xe8, 0x35, 0x74,
	0xa9, 0x4f, 0x94, 0xec, 0xb7, 0xb4, 0xf1, 0x92, 0xf2, 0x92, 0xa2, 0x2f, 0x92, 0xfd, 0x16, 0x7d,
	0x0a, 0x4d, 0x3a, 0x27, 0x6d, 0x14, 0x4d, 0xcf, 0x24, 0x1e, 0x38, 0x5a, 0xb1, 0x43, 0x40, 0x2d,
	0xe8, 0x27, 0xd0, 0x5e, 0xa5, 0x59, 0xb4, 0x59, 0x27, 0xb4, 0x6f, 0x34, 0xbd, 0x13, 0x3e, 0x17,
	0xf9, 0xf3, 0xb0, 0x30, 0x22, 0x07, 0x8c, 0x28, 0x99, 0xd0, 0x26, 0xb2, 0xc7, 0x9a, 0x6c, 0x4e,
	0x34, 0xbe, 0x48, 0x30, 0x31, 0xa1, 0xd7, 0xc4, 0xc3, 0xa3, 0xed, 0x64, 0x8f, 0x65, 0xa5, 0xf0,
	0x98, 0x87, 0x19, 0xf7, 0xf2, 0xd0, 0x08, 0xf4, 0xf5, 0x2d, 0xed, 0x2d, 0xcd, 0xba, 0xd3, 0xed,
	0xf8, 0xed, 0x2d, 0xd6, 0xd7, 0xb7, 0x36, 0x6d, 0x9c, 0xb3, 0x63, 0xa7, 0xc9, 0xfe, 0xb7, 0xce,
	0xfa, 0xf5, 0x57, 0xd0, 0x58, 0x84, 0x99, 0xc8, 0xe5, 0x7e, 0x6d, 0x46, 0x4c, 0x8d, 0xff, 0xf7,
	0xfe, 0x9f, 0x43, 0x4f, 0xec, 0x29, 0x85, 0x4c, 0x68, 0xb7, 0x79, 0x7f, 0x16, 0x9c, 0x0a, 0x04,
	0x51, 0x4d, 0xd0, 0x4b, 0xba, 0x2e, 0x8f, 0x6f, 0x6e, 0x19, 0x74, 0xb1, 0x26, 0x4f, 0xc4, 0xd2,
	0x78, 0x30, 0x96, 0x8d, 0x7b, 0x63, 0x69, 0xbf, 0xa2, 0x17, 0x0c, 0xf6, 0x73, 0xd0, 0xdf, 0x1e,
	0xbd, 0x66, 0xb0, 0xa7, 0xf7, 0x06, 0x73, 0xf4, 0x18, 0xf4, 0x8b, 0x04, 0xb5, 0x40, 0x3f, 0xff,
	0x62, 0xf0, 0x88, 0x3e, 0x27, 0x03, 0xed, 0x88, 0xf6, 0x9f, 0x1a, 0x34, 0xff, 0x94, 0x44, 0xe9,
	0xea, 0xe8, 0x55, 0x89, 0x75, 0x78, 0x55, 0xf2, 0xee, 0x91, 0xb8, 0x2c, 0x29, 0x2d, 0x53, 0xfa,
	0xda, 0x95, 0x65, 0x5a, 0x5a, 0xd8, 0xc5, 0x45, 0xf7, 0x9d, 0xc6, 0x2d, 0xb3, 0xd2, 0xf2, 0x25,
	0x4d, 0xbb, 0xca, 0xf2, 0x65, 0x69, 0xf1, 0x69, 0xba, 0x75, 0xdf, 0xe9, 0xdc, 0xe2, 0xcf, 0x3b,
	0xd0, 0xa2, 0x4b, 0x9c, 0x94, 0x23, 0xaf, 0x1c, 0x4d, 0x7f, 0xfe, 0x8a, 0x05, 0xa3, 0x03, 0x8d,
	0xf9, 0x39, 0x9e, 0x0c, 0x1e, 0xf1, 0x91, 0x37, 0xd0, 0xf8, 0x68, 0x3a, 0xd0, 0xbd, 0xff, 0xe8,
	0x00, 0x6f, 0xca, 0x9b, 0x2c, 0xf4, 0x1a, 0x3a, 0xfc, 0x9a, 0x26, 0x40, 0x74, 0x33, 0xb9, 0x64,
	0xcb, 0x02, 0xfa, 0x29, 0x74, 0xc5, 0xc5, 0x42, 0x80, 0x4e, 0xd8, 0x8e, 0x31, 0xd1, 0x3e, 0x90,
	0xd0, 0x33, 0x68, 0x92, 0x6f, 0xd5, 0x00, 0x75, 0xc4, 0x67, 0xab, 0x5d, 0x8e, 0xd0, 0x8f, 0xa1,
	0x71, 0x9e, 0xdc, 0x04, 0xe8, 0xf1, 0x9d, 0x6c, 0x3b, 0x4f, 0x6e, 0x6c, 0x7a, 0xc2, 0xc9, 0xff,
	0x99, 0x5f, 0xf0, 0x9b, 0xaf, 0x00, 0x1d, 0xa9, 0x7e, 0x76, 0xb7, 0xac, 0xc8, 0x68, 0x0c, 0x6d,
	0x3a, 0xf0, 0x02, 0xa4, 0xf8, 0x5f, 0x61, 0xf7, 0x6b, 0xb5, 0x1b, 0x7d, 0xca, 0xfd, 0xa7, 0x01,
	0x92, 0xee, 0xc9, 0x6c, 0x69, 0x8c, 0x2c, 0x68, 0xe0, 0x68, 0x15, 0xa0, 0x36, 0xcf, 0x4c, 0x5b,
	0x0c, 0xd0, 0x0b, 0x1e, 0xea, 0x00, 0xd1, 0x15, 0xd0, 0xb1, 0x5d, 0x0d, 0xd1, 0x08, 0xe0, 0x4d,
	0x18, 0xc7, 0x7f, 0xd9, 0x14, 0xdf, 0xbd, 0xbf, 0x46, 0xd5, 0x2a, 0xa5, 0x05, 0xcf, 0x27, 0x7f,
	0x3d, 0x5b, 0x6f, 0x8a, 0xef, 0xf6, 0x8b, 0xf1, 0x32, 0xdd, 0x9e, 0x5d, 0x87, 0xc9, 0x26, 0x8a,
	0x3f, 0xc4, 0xe1, 0xf5, 0x32, 0x3d, 0x5b, 0xa7, 0x9f, 0xd3, 0x17, 0xfd, 0x7c, 0xfd, 0xf7, 0xf8,
	0x8c, 0xdf, 0x3a, 0x7e, 0xb5, 0x5b, 0x2c, 0x5a, 0x54, 0x3b, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xed, 0xe4, 0xf1, 0x05, 0x8a, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConstructsClient is the client API for Constructs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConstructsClient interface {
	Scalars_(ctx context.Context, in *Scalars, opts ...grpc.CallOption) (*Scalars, error)
	Repeated_(ctx context.Context, in *Repeated, opts ...grpc.CallOption) (*Repeated, error)
	Maps_(ctx context.Context, in *Maps, opts ...grpc.CallOption) (*Maps, error)
	Any_(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*Any, error)
	Empty_(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Empty, error)
	Empty2_(ctx context.Context, in *EmptyRecursive, opts ...grpc.CallOption) (*EmptyNested, error)
	Empty3_(ctx context.Context, in *Empty3, opts ...grpc.CallOption) (*Empty3, error)
	Ref_(ctx context.Context, in *Ref, opts ...grpc.CallOption) (*Ref, error)
	Oneof_(ctx context.Context, in *Oneof, opts ...grpc.CallOption) (*Oneof, error)
	CallWithId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type constructsClient struct {
	cc *grpc.ClientConn
}

func NewConstructsClient(cc *grpc.ClientConn) ConstructsClient {
	return &constructsClient{cc}
}

func (c *constructsClient) Scalars_(ctx context.Context, in *Scalars, opts ...grpc.CallOption) (*Scalars, error) {
	out := new(Scalars)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Scalars_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Repeated_(ctx context.Context, in *Repeated, opts ...grpc.CallOption) (*Repeated, error) {
	out := new(Repeated)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Repeated_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Maps_(ctx context.Context, in *Maps, opts ...grpc.CallOption) (*Maps, error) {
	out := new(Maps)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Maps_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Any_(ctx context.Context, in *any.Any, opts ...grpc.CallOption) (*Any, error) {
	out := new(Any)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Any_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Empty_(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Empty_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Empty2_(ctx context.Context, in *EmptyRecursive, opts ...grpc.CallOption) (*EmptyNested, error) {
	out := new(EmptyNested)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Empty2_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Empty3_(ctx context.Context, in *Empty3, opts ...grpc.CallOption) (*Empty3, error) {
	out := new(Empty3)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Empty3_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Ref_(ctx context.Context, in *Ref, opts ...grpc.CallOption) (*Ref, error) {
	out := new(Ref)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Ref_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) Oneof_(ctx context.Context, in *Oneof, opts ...grpc.CallOption) (*Oneof, error) {
	out := new(Oneof)
	err := c.cc.Invoke(ctx, "/pb.Constructs/Oneof_", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *constructsClient) CallWithId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Constructs/CallWithId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConstructsServer is the server API for Constructs service.
type ConstructsServer interface {
	Scalars_(context.Context, *Scalars) (*Scalars, error)
	Repeated_(context.Context, *Repeated) (*Repeated, error)
	Maps_(context.Context, *Maps) (*Maps, error)
	Any_(context.Context, *any.Any) (*Any, error)
	Empty_(context.Context, *empty.Empty) (*Empty, error)
	Empty2_(context.Context, *EmptyRecursive) (*EmptyNested, error)
	Empty3_(context.Context, *Empty3) (*Empty3, error)
	Ref_(context.Context, *Ref) (*Ref, error)
	Oneof_(context.Context, *Oneof) (*Oneof, error)
	CallWithId(context.Context, *Empty) (*Empty, error)
}

func RegisterConstructsServer(s *grpc.Server, srv ConstructsServer) {
	s.RegisterService(&_Constructs_serviceDesc, srv)
}

func _Constructs_Scalars__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scalars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Scalars_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Scalars_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Scalars_(ctx, req.(*Scalars))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Repeated__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repeated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Repeated_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Repeated_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Repeated_(ctx, req.(*Repeated))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Maps__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Maps)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Maps_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Maps_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Maps_(ctx, req.(*Maps))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Any__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(any.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Any_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Any_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Any_(ctx, req.(*any.Any))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Empty__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Empty_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Empty_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Empty_(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Empty2__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRecursive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Empty2_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Empty2_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Empty2_(ctx, req.(*EmptyRecursive))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Empty3__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Empty3_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Empty3_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Empty3_(ctx, req.(*Empty3))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Ref__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ref)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Ref_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Ref_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Ref_(ctx, req.(*Ref))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_Oneof__Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oneof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).Oneof_(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/Oneof_",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).Oneof_(ctx, req.(*Oneof))
	}
	return interceptor(ctx, in, info, handler)
}

func _Constructs_CallWithId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConstructsServer).CallWithId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Constructs/CallWithId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConstructsServer).CallWithId(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Constructs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Constructs",
	HandlerType: (*ConstructsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scalars_",
			Handler:    _Constructs_Scalars__Handler,
		},
		{
			MethodName: "Repeated_",
			Handler:    _Constructs_Repeated__Handler,
		},
		{
			MethodName: "Maps_",
			Handler:    _Constructs_Maps__Handler,
		},
		{
			MethodName: "Any_",
			Handler:    _Constructs_Any__Handler,
		},
		{
			MethodName: "Empty_",
			Handler:    _Constructs_Empty__Handler,
		},
		{
			MethodName: "Empty2_",
			Handler:    _Constructs_Empty2__Handler,
		},
		{
			MethodName: "Empty3_",
			Handler:    _Constructs_Empty3__Handler,
		},
		{
			MethodName: "Ref_",
			Handler:    _Constructs_Ref__Handler,
		},
		{
			MethodName: "Oneof_",
			Handler:    _Constructs_Oneof__Handler,
		},
		{
			MethodName: "CallWithId",
			Handler:    _Constructs_CallWithId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/constructs.proto",
}
