// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/constructs.proto

package pb // import "github.com/danielvladco/go-proto-gql/example"

import fmt "fmt"
import io "io"
import github_com_99designs_gqlgen_graphql "github.com/99designs/gqlgen/graphql"
import encoding_json "encoding/json"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func MarshalMaps_Int32Int32Entry(mp map[int32]int32) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Int32Int32Entry(v interface{}) (mp map[int32]int32, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[int32]int32", v)
	}
}

func MarshalMaps_Int64Int64Entry(mp map[int64]int64) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Int64Int64Entry(v interface{}) (mp map[int64]int64, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[int64]int64", v)
	}
}

func MarshalMaps_Uint32Uint32Entry(mp map[uint32]uint32) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Uint32Uint32Entry(v interface{}) (mp map[uint32]uint32, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[uint32]uint32", v)
	}
}

func MarshalMaps_Uint64Uint64Entry(mp map[uint64]uint64) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Uint64Uint64Entry(v interface{}) (mp map[uint64]uint64, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[uint64]uint64", v)
	}
}

func MarshalMaps_Sint32Sint32Entry(mp map[int32]int32) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Sint32Sint32Entry(v interface{}) (mp map[int32]int32, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[int32]int32", v)
	}
}

func MarshalMaps_Sint64Sint64Entry(mp map[int64]int64) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Sint64Sint64Entry(v interface{}) (mp map[int64]int64, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[int64]int64", v)
	}
}

func MarshalMaps_Fixed32Fixed32Entry(mp map[uint32]uint32) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Fixed32Fixed32Entry(v interface{}) (mp map[uint32]uint32, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[uint32]uint32", v)
	}
}

func MarshalMaps_Fixed64Fixed64Entry(mp map[uint64]uint64) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Fixed64Fixed64Entry(v interface{}) (mp map[uint64]uint64, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[uint64]uint64", v)
	}
}

func MarshalMaps_Sfixed32Sfixed32Entry(mp map[int32]int32) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Sfixed32Sfixed32Entry(v interface{}) (mp map[int32]int32, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[int32]int32", v)
	}
}

func MarshalMaps_Sfixed64Sfixed64Entry(mp map[int64]int64) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_Sfixed64Sfixed64Entry(v interface{}) (mp map[int64]int64, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[int64]int64", v)
	}
}

func MarshalMaps_BoolBoolEntry(mp map[bool]bool) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_BoolBoolEntry(v interface{}) (mp map[bool]bool, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[bool]bool", v)
	}
}

func MarshalMaps_StringStringEntry(mp map[string]string) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_StringStringEntry(v interface{}) (mp map[string]string, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[string]string", v)
	}
}

func MarshalMaps_StringBytesEntry(mp map[string][]byte) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_StringBytesEntry(v interface{}) (mp map[string][]byte, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[string][]byte", v)
	}
}

func MarshalMaps_StringFloatEntry(mp map[string]float32) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_StringFloatEntry(v interface{}) (mp map[string]float32, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[string]float32", v)
	}
}

func MarshalMaps_StringDoubleEntry(mp map[string]float64) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_StringDoubleEntry(v interface{}) (mp map[string]float64, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[string]float64", v)
	}
}

func MarshalMaps_StringFooEntry(mp map[string]*Foo) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_StringFooEntry(v interface{}) (mp map[string]*Foo, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[string]*Foo", v)
	}
}

func MarshalMaps_StringBarEntry(mp map[string]Bar) github_com_99designs_gqlgen_graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := encoding_json.NewEncoder(w).Encode(mp)
		if err != nil {
			panic("stupid map")
		}
	})
}

func UnmarshalMaps_StringBarEntry(v interface{}) (mp map[string]Bar, err error) {
	switch vv := v.(type) {
	case []byte:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	case encoding_json.RawMessage:
		err = encoding_json.Unmarshal(vv, &mp)
		return mp, err
	default:
		return nil, fmt.Errorf("%T is not map[string]Bar", v)
	}
}

func (c *Bar) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = Bar(Bar_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal Bar enum")
}

func (c Bar) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}

func (c *Ref_Foo_En) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = Ref_Foo_En(Ref_Foo_En_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal Ref_Foo_En enum")
}

func (c Ref_Foo_En) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}

func (c *Ref_Foo_Bar_En) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = Ref_Foo_Bar_En(Ref_Foo_Bar_En_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal Ref_Foo_Bar_En enum")
}

func (c Ref_Foo_Bar_En) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}
