// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/options.proto

package pb // import "github.com/danielvladco/go-proto-gql/example"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/danielvladco/go-proto-gql"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
