site_name: API Adapter
site_dir: .mkdocs
repo_url: https://github.com/danielvladco/go-proto-gql
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.superfences

theme:
  name: material
  palette:
    - scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
  #    - navigation.sections

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo