// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

/*
Package gql is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Res
	Req
*/
package gql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var schema = `
type schema {
	query: Query
	mutation: Mutation
}
type Mutation {
}
type Query {
}
`
