// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gql1.proto

/*
Package gql is a generated protocol buffer package.

It is generated from these files:
	gql1.proto
	gql2.proto

It has these top-level messages:
	Res
	Req
	New
	Res1
	Req1
	New1
*/
package gql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var schema = `
type schema {
	query: Query
	mutation: Mutation
}
type Mutation {
	# please false
	gql_Svx_MM(input: .gql.Req!): .gql.Res_Out
}
type Mutation {
	# please false
	gql_Svx_MM1(input: .gql.Req!): .gql.New_Out
}
type Mutation {
	# please false
	gql_Svx_MM2(input: .gql.Req!): .gql.Res_Out
}
type Mutation {
	# please false
	gql_Svx_MM3(input: .gql.Req!): .gql.Res_Out
}
type Mutation {
	# please false
	gql_Svx_MM4(input: .gql.Req!): .gql.Res_Out
}
type Mutation {
	# please false
	gql_Svx_SS1(input: .gql.Req!): .gql.New.Type.E_Out
}
type Mutation {
	# please false
	gql_Svx_SS2(input: .gql.Req!): .gql.New.Type_Out
}
type Mutation {
	# please false
	gql_Svx_SS3(input: .gql.Req!): .gql.Res_Out
}
#11E
#.google_protobuf..FieldDescriptorProto > 
#.google_protobuf..MethodDescriptorProto > 
#.google_protobuf..EnumValueOptions > 
#.google_protobuf.Annotation..GeneratedCodeInfo > 
#.google_protobuf..EnumValueDescriptorProto > 
#.google_protobuf..FileDescriptorSet > 
#.google_protobuf..OneofDescriptorProto > 
#.google_protobuf..EnumReservedRange > 
#.google_protobuf..ServiceDescriptorProto > 
#.google_protobuf..EnumOptions > 
#.google_protobuf..NamePart > 
#.gql..Res > 
#.google_protobuf..FileDescriptorProto > 
#.google_protobuf..Annotation > 
#.gql..Req > 
#.gql.Type..New > 
#.google_protobuf..ExtensionRange > 
#.google_protobuf..ReservedRange > 
#.google_protobuf..ExtensionRangeOptions > 
#.google_protobuf.EnumReservedRange..EnumDescriptorProto > 
#.google_protobuf..OneofOptions > 
#.google_protobuf..MethodOptions > 
#.google_protobuf..Location > 
#.google_protobuf.NamePart..UninterpretedOption > 
#.gql.E..Type > 
#.gql..E > 
#.google_protobuf..FileOptions > 
#.google_protobuf..MessageOptions > 
#.google_protobuf..FieldOptions > 
#.google_protobuf.ExtensionRange.ReservedRange..DescriptorProto > 
#.google_protobuf..ServiceOptions > 
#.google_protobuf.Location..SourceCodeInfo > 
`
