// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	SignInReq
	GetCurrentAccountReq
	SignUpWithEmailReq
	ResendConfirmationEmailReq
	SignOutReq
	ConfirmEmailReq
	ForgotPasswordReq
	CheckResetPasswordTokenReq
	RequestChangeEmailReq
	ChangeEmailReq
	ResetPasswordReq
	ChangePasswordReq
	RequestDeleteAccountReq
	DeleteAccountReq
	SignInRes
	SignUpWithEmailRes
	ConfirmEmailRes
	GetCurrentAccountRes
	CheckResetPasswordTokenRes
	SignOutRes
	ResendConfirmationEmailRes
	ForgotPasswordRes
	ResetPasswordRes
	ChangePasswordRes
	RequestChangeEmailRes
	ChangeEmailRes
	RequestDeleteAccountRes
	DeleteAccountRes
	Account
	SignedUpWithEmail
	EmailConfirmed
	PasswordReset
	PasswordChanged
	EmailChanged
	AccountDeleted
*/
package account

import fmt "fmt"
import io "io"
import proto "github.com/gogo/protobuf/proto"
import math "math"
import _ "github.com/danielvladco/go-proto-gql"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (c *ResendConfirmationEmailReq_Inner_InnerEnum) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = ResendConfirmationEmailReq_Inner_InnerEnum(ResendConfirmationEmailReq_Inner_InnerEnum_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal ResendConfirmationEmailReq_Inner_InnerEnum enum")
}

func (c ResendConfirmationEmailReq_Inner_InnerEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, c.String())
}

func (c *ResendConfirmationEmailReq_Data) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = ResendConfirmationEmailReq_Data(ResendConfirmationEmailReq_Data_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal ResendConfirmationEmailReq_Data enum")
}

func (c ResendConfirmationEmailReq_Data) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, c.String())
}
