// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/account/account.proto

package account // import "github.com/danielvladco/go-proto-gql/examples/account"

import fmt "fmt"
import io "io"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/danielvladco/go-proto-gql"
import _ "github.com/danielvladco/go-proto-gql/examples/account/datatypes"
import _ "github.com/mwitkow/go-proto-validators@v0.0.0-20180403085117-0950a7990007"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (c *Roles) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = Roles(Roles_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal Roles enum")
}

func (c Roles) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}

func (c *ResendConfirmationEmailReq_Data) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = ResendConfirmationEmailReq_Data(ResendConfirmationEmailReq_Data_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal ResendConfirmationEmailReq_Data enum")
}

func (c ResendConfirmationEmailReq_Data) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}

func (c *ResendConfirmationEmailReq_Inner_InnerEnum) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = ResendConfirmationEmailReq_Inner_InnerEnum(ResendConfirmationEmailReq_Inner_InnerEnum_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal ResendConfirmationEmailReq_Inner_InnerEnum enum")
}

func (c ResendConfirmationEmailReq_Inner_InnerEnum) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}
