// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/account/auth.proto

package account // import "github.com/danielvladco/go-proto-gql/examples/account"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/danielvladco/go-proto-gql"
import _ "github.com/mwitkow/go-proto-validators@v0.0.0-20180403085117-0950a7990007"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Roles1 int32

const (
	Roles1_DDD1 Roles1 = 0
	Roles1_NNN1 Roles1 = 1
	Roles1_GGG1 Roles1 = 2
)

var Roles1_name = map[int32]string{
	0: "DDD1",
	1: "NNN1",
	2: "GGG1",
}
var Roles1_value = map[string]int32{
	"DDD1": 0,
	"NNN1": 1,
	"GGG1": 2,
}

func (x Roles1) String() string {
	return proto.EnumName(Roles1_name, int32(x))
}
func (Roles1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{0}
}

type SignInReq1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReq1) Reset()         { *m = SignInReq1{} }
func (m *SignInReq1) String() string { return proto.CompactTextString(m) }
func (*SignInReq1) ProtoMessage()    {}
func (*SignInReq1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{0}
}
func (m *SignInReq1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq1.Unmarshal(m, b)
}
func (m *SignInReq1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq1.Marshal(b, m, deterministic)
}
func (dst *SignInReq1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq1.Merge(dst, src)
}
func (m *SignInReq1) XXX_Size() int {
	return xxx_messageInfo_SignInReq1.Size(m)
}
func (m *SignInReq1) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq1.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq1 proto.InternalMessageInfo

func (m *SignInReq1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInReq1) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetCurrentAccountReq1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentAccountReq1) Reset()         { *m = GetCurrentAccountReq1{} }
func (m *GetCurrentAccountReq1) String() string { return proto.CompactTextString(m) }
func (*GetCurrentAccountReq1) ProtoMessage()    {}
func (*GetCurrentAccountReq1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{1}
}
func (m *GetCurrentAccountReq1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentAccountReq1.Unmarshal(m, b)
}
func (m *GetCurrentAccountReq1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentAccountReq1.Marshal(b, m, deterministic)
}
func (dst *GetCurrentAccountReq1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentAccountReq1.Merge(dst, src)
}
func (m *GetCurrentAccountReq1) XXX_Size() int {
	return xxx_messageInfo_GetCurrentAccountReq1.Size(m)
}
func (m *GetCurrentAccountReq1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentAccountReq1.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentAccountReq1 proto.InternalMessageInfo

type SignUpWithEmailReq1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpWithEmailReq1) Reset()         { *m = SignUpWithEmailReq1{} }
func (m *SignUpWithEmailReq1) String() string { return proto.CompactTextString(m) }
func (*SignUpWithEmailReq1) ProtoMessage()    {}
func (*SignUpWithEmailReq1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{2}
}
func (m *SignUpWithEmailReq1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpWithEmailReq1.Unmarshal(m, b)
}
func (m *SignUpWithEmailReq1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpWithEmailReq1.Marshal(b, m, deterministic)
}
func (dst *SignUpWithEmailReq1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpWithEmailReq1.Merge(dst, src)
}
func (m *SignUpWithEmailReq1) XXX_Size() int {
	return xxx_messageInfo_SignUpWithEmailReq1.Size(m)
}
func (m *SignUpWithEmailReq1) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpWithEmailReq1.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpWithEmailReq1 proto.InternalMessageInfo

func (m *SignUpWithEmailReq1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpWithEmailReq1) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResendConfirmationEmailReq1 struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendConfirmationEmailReq1) Reset()         { *m = ResendConfirmationEmailReq1{} }
func (m *ResendConfirmationEmailReq1) String() string { return proto.CompactTextString(m) }
func (*ResendConfirmationEmailReq1) ProtoMessage()    {}
func (*ResendConfirmationEmailReq1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{3}
}
func (m *ResendConfirmationEmailReq1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendConfirmationEmailReq1.Unmarshal(m, b)
}
func (m *ResendConfirmationEmailReq1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendConfirmationEmailReq1.Marshal(b, m, deterministic)
}
func (dst *ResendConfirmationEmailReq1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendConfirmationEmailReq1.Merge(dst, src)
}
func (m *ResendConfirmationEmailReq1) XXX_Size() int {
	return xxx_messageInfo_ResendConfirmationEmailReq1.Size(m)
}
func (m *ResendConfirmationEmailReq1) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendConfirmationEmailReq1.DiscardUnknown(m)
}

var xxx_messageInfo_ResendConfirmationEmailReq1 proto.InternalMessageInfo

func (m *ResendConfirmationEmailReq1) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type SignInRes1 struct {
	Account              *Account1 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignInRes1) Reset()         { *m = SignInRes1{} }
func (m *SignInRes1) String() string { return proto.CompactTextString(m) }
func (*SignInRes1) ProtoMessage()    {}
func (*SignInRes1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{4}
}
func (m *SignInRes1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRes1.Unmarshal(m, b)
}
func (m *SignInRes1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRes1.Marshal(b, m, deterministic)
}
func (dst *SignInRes1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRes1.Merge(dst, src)
}
func (m *SignInRes1) XXX_Size() int {
	return xxx_messageInfo_SignInRes1.Size(m)
}
func (m *SignInRes1) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRes1.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRes1 proto.InternalMessageInfo

func (m *SignInRes1) GetAccount() *Account1 {
	if m != nil {
		return m.Account
	}
	return nil
}

type SignUpWithEmailRes1 struct {
	Account              *Account1 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignUpWithEmailRes1) Reset()         { *m = SignUpWithEmailRes1{} }
func (m *SignUpWithEmailRes1) String() string { return proto.CompactTextString(m) }
func (*SignUpWithEmailRes1) ProtoMessage()    {}
func (*SignUpWithEmailRes1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{5}
}
func (m *SignUpWithEmailRes1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpWithEmailRes1.Unmarshal(m, b)
}
func (m *SignUpWithEmailRes1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpWithEmailRes1.Marshal(b, m, deterministic)
}
func (dst *SignUpWithEmailRes1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpWithEmailRes1.Merge(dst, src)
}
func (m *SignUpWithEmailRes1) XXX_Size() int {
	return xxx_messageInfo_SignUpWithEmailRes1.Size(m)
}
func (m *SignUpWithEmailRes1) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpWithEmailRes1.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpWithEmailRes1 proto.InternalMessageInfo

func (m *SignUpWithEmailRes1) GetAccount() *Account1 {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetCurrentAccountRes1 struct {
	Account              []*Account1 `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCurrentAccountRes1) Reset()         { *m = GetCurrentAccountRes1{} }
func (m *GetCurrentAccountRes1) String() string { return proto.CompactTextString(m) }
func (*GetCurrentAccountRes1) ProtoMessage()    {}
func (*GetCurrentAccountRes1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{6}
}
func (m *GetCurrentAccountRes1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentAccountRes1.Unmarshal(m, b)
}
func (m *GetCurrentAccountRes1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentAccountRes1.Marshal(b, m, deterministic)
}
func (dst *GetCurrentAccountRes1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentAccountRes1.Merge(dst, src)
}
func (m *GetCurrentAccountRes1) XXX_Size() int {
	return xxx_messageInfo_GetCurrentAccountRes1.Size(m)
}
func (m *GetCurrentAccountRes1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentAccountRes1.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentAccountRes1 proto.InternalMessageInfo

func (m *GetCurrentAccountRes1) GetAccount() []*Account1 {
	if m != nil {
		return m.Account
	}
	return nil
}

type ResendConfirmationEmailRes1 struct {
	Acc                  *Account1 `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResendConfirmationEmailRes1) Reset()         { *m = ResendConfirmationEmailRes1{} }
func (m *ResendConfirmationEmailRes1) String() string { return proto.CompactTextString(m) }
func (*ResendConfirmationEmailRes1) ProtoMessage()    {}
func (*ResendConfirmationEmailRes1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{7}
}
func (m *ResendConfirmationEmailRes1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendConfirmationEmailRes1.Unmarshal(m, b)
}
func (m *ResendConfirmationEmailRes1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendConfirmationEmailRes1.Marshal(b, m, deterministic)
}
func (dst *ResendConfirmationEmailRes1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendConfirmationEmailRes1.Merge(dst, src)
}
func (m *ResendConfirmationEmailRes1) XXX_Size() int {
	return xxx_messageInfo_ResendConfirmationEmailRes1.Size(m)
}
func (m *ResendConfirmationEmailRes1) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendConfirmationEmailRes1.DiscardUnknown(m)
}

var xxx_messageInfo_ResendConfirmationEmailRes1 proto.InternalMessageInfo

func (m *ResendConfirmationEmailRes1) GetAcc() *Account1 {
	if m != nil {
		return m.Acc
	}
	return nil
}

// common
type Account1 struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmailConfirmed       bool     `protobuf:"varint,3,opt,name=email_confirmed,json=emailConfirmed,proto3" json:"email_confirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account1) Reset()         { *m = Account1{} }
func (m *Account1) String() string { return proto.CompactTextString(m) }
func (*Account1) ProtoMessage()    {}
func (*Account1) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_e0806feaec53e8ef, []int{8}
}
func (m *Account1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account1.Unmarshal(m, b)
}
func (m *Account1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account1.Marshal(b, m, deterministic)
}
func (dst *Account1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account1.Merge(dst, src)
}
func (m *Account1) XXX_Size() int {
	return xxx_messageInfo_Account1.Size(m)
}
func (m *Account1) XXX_DiscardUnknown() {
	xxx_messageInfo_Account1.DiscardUnknown(m)
}

var xxx_messageInfo_Account1 proto.InternalMessageInfo

func (m *Account1) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account1) GetEmailConfirmed() bool {
	if m != nil {
		return m.EmailConfirmed
	}
	return false
}

func init() {
	proto.RegisterType((*SignInReq1)(nil), "account.SignInReq1")
	proto.RegisterType((*GetCurrentAccountReq1)(nil), "account.GetCurrentAccountReq1")
	proto.RegisterType((*SignUpWithEmailReq1)(nil), "account.SignUpWithEmailReq1")
	proto.RegisterType((*ResendConfirmationEmailReq1)(nil), "account.ResendConfirmationEmailReq1")
	proto.RegisterType((*SignInRes1)(nil), "account.SignInRes1")
	proto.RegisterType((*SignUpWithEmailRes1)(nil), "account.SignUpWithEmailRes1")
	proto.RegisterType((*GetCurrentAccountRes1)(nil), "account.GetCurrentAccountRes1")
	proto.RegisterType((*ResendConfirmationEmailRes1)(nil), "account.ResendConfirmationEmailRes1")
	proto.RegisterType((*Account1)(nil), "account.Account1")
	proto.RegisterEnum("account.Roles1", Roles1_name, Roles1_value)
}

func init() { proto.RegisterFile("examples/account/auth.proto", fileDescriptor_auth_e0806feaec53e8ef) }

var fileDescriptor_auth_e0806feaec53e8ef = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x9c, 0xb6, 0x69, 0x7a, 0x3f, 0x89, 0xb6, 0x53, 0x50, 0x2b, 0x17, 0x48, 0x65, 0xda,
	0x52, 0x51, 0x6c, 0xcf, 0xa4, 0x8d, 0xd2, 0x08, 0x21, 0x9a, 0x1f, 0x14, 0x55, 0x88, 0x2c, 0x1c,
	0x21, 0x42, 0x69, 0x89, 0xa6, 0xb6, 0x49, 0x2c, 0x1c, 0x4f, 0x62, 0x3b, 0x49, 0x05, 0x62, 0xc1,
	0x96, 0xa7, 0xe1, 0x49, 0x78, 0x85, 0xa0, 0x3c, 0x09, 0xf2, 0x5f, 0x52, 0xf2, 0x07, 0x2c, 0x58,
	0x65, 0xee, 0xb9, 0x77, 0x4e, 0x8e, 0xcf, 0x99, 0x19, 0xd8, 0xd6, 0xaf, 0x69, 0xb3, 0x65, 0xea,
	0x8e, 0x4c, 0x55, 0x95, 0x75, 0x2c, 0x57, 0xa6, 0x1d, 0xb7, 0x21, 0xb5, 0x6c, 0xe6, 0x32, 0xb4,
	0x1c, 0x62, 0xfc, 0x4a, 0xbd, 0x6d, 0x06, 0x18, 0xff, 0xa6, 0x6e, 0xb8, 0x8d, 0xce, 0x95, 0xa4,
	0xb2, 0xa6, 0xdc, 0xec, 0x19, 0xee, 0x07, 0xd6, 0x93, 0xeb, 0x4c, 0xf4, 0x9b, 0x62, 0x97, 0x9a,
	0x86, 0x46, 0x5d, 0x66, 0x3b, 0xa7, 0x5d, 0x2c, 0x61, 0x09, 0x8b, 0x29, 0x4c, 0x4e, 0xf0, 0x31,
	0x3e, 0xc2, 0x27, 0x69, 0x42, 0x32, 0x22, 0xce, 0xa6, 0x31, 0xcd, 0x64, 0xb3, 0x18, 0xe3, 0x8c,
	0x3c, 0x9c, 0x0e, 0xa8, 0x85, 0x2f, 0x1c, 0x40, 0xc5, 0xa8, 0x5b, 0x67, 0x96, 0xa2, 0xb7, 0x09,
	0x7a, 0x01, 0x4b, 0x7a, 0x93, 0x1a, 0xe6, 0x16, 0xb7, 0xc3, 0x1d, 0xac, 0xe4, 0xd3, 0x83, 0x7e,
	0x92, 0x80, 0xf8, 0xee, 0x2d, 0x15, 0x3f, 0xe6, 0xc4, 0x73, 0x2c, 0x66, 0xa5, 0xda, 0xde, 0xe1,
	0x85, 0x78, 0x79, 0x78, 0xea, 0x41, 0x5e, 0xed, 0x15, 0x17, 0x92, 0x57, 0x5d, 0x7e, 0x4a, 0x3d,
	0x3e, 0xfe, 0xbc, 0x5b, 0xe5, 0x94, 0x80, 0x03, 0xed, 0x43, 0xa2, 0x45, 0x1d, 0xa7, 0xc7, 0x6c,
	0x6d, 0x2b, 0xe6, 0xf3, 0xc1, 0xa0, 0x9f, 0x8c, 0x57, 0xb9, 0xd6, 0xd2, 0xb5, 0xa6, 0x0c, 0x7b,
	0xc2, 0x26, 0xdc, 0x29, 0xe9, 0x6e, 0xa1, 0x63, 0xdb, 0xba, 0xe5, 0xe6, 0x82, 0xcf, 0xf7, 0xd4,
	0x08, 0x5f, 0x39, 0xd8, 0xf0, 0xc4, 0xbd, 0x6a, 0xbd, 0x36, 0xdc, 0xc6, 0x73, 0x8f, 0xf4, 0xdf,
	0xaa, 0x5c, 0x9c, 0xa3, 0xb2, 0x08, 0xdb, 0x8a, 0xee, 0xe8, 0x96, 0x56, 0x60, 0xd6, 0x7b, 0xc3,
	0x6e, 0x52, 0xd7, 0x60, 0xd6, 0x48, 0xd3, 0x1e, 0x40, 0x98, 0x5c, 0xcd, 0xd0, 0x42, 0x61, 0xf1,
	0x41, 0x3f, 0x19, 0xab, 0x72, 0xca, 0x4a, 0xd8, 0x39, 0xd3, 0x84, 0xec, 0xc8, 0x6e, 0x87, 0xa0,
	0x43, 0x88, 0xe2, 0xf6, 0x77, 0xfc, 0x9f, 0x5a, 0x97, 0xc2, 0x5a, 0x0a, 0x7d, 0x20, 0x4a, 0x34,
	0x21, 0xe4, 0xa7, 0x98, 0xf1, 0xb7, 0x1c, 0xc5, 0xa9, 0x56, 0x8f, 0xb3, 0x2c, 0xfc, 0x56, 0xc9,
	0x6c, 0x2b, 0x1c, 0x82, 0x1e, 0xc0, 0x02, 0x55, 0xd5, 0xd9, 0x6a, 0xbc, 0xae, 0xd0, 0x80, 0x44,
	0x04, 0xa0, 0x7b, 0x93, 0xde, 0xdd, 0xf0, 0x0c, 0xdd, 0x8e, 0xe2, 0xf6, 0x0f, 0x51, 0x94, 0xdb,
	0x43, 0x58, 0xf5, 0x17, 0x35, 0x35, 0x10, 0xa1, 0x6b, 0x5b, 0x0b, 0x3b, 0xdc, 0x41, 0x42, 0xb9,
	0xe5, 0xc3, 0x85, 0x08, 0x7d, 0xb4, 0x0f, 0x71, 0x85, 0x99, 0x9e, 0xb0, 0x04, 0x2c, 0x16, 0x8b,
	0x45, 0xb2, 0xf6, 0x9f, 0xb7, 0x2a, 0x97, 0xcb, 0x64, 0x8d, 0xf3, 0x56, 0xa5, 0x52, 0x89, 0xac,
	0xc5, 0x52, 0xdf, 0x63, 0xb0, 0x9c, 0xeb, 0xb8, 0x8d, 0x4a, 0x57, 0x45, 0x29, 0x88, 0x07, 0x31,
	0xa1, 0x8d, 0xa1, 0xfe, 0xd1, 0x35, 0xe1, 0x27, 0x41, 0x87, 0xa0, 0x0a, 0xac, 0x4f, 0x78, 0x8b,
	0xee, 0x0f, 0x27, 0xa7, 0x1e, 0x71, 0x7e, 0x6e, 0xdf, 0x21, 0xe8, 0x25, 0xac, 0x8e, 0x85, 0x8e,
	0xee, 0xfe, 0xf2, 0xe7, 0x63, 0x77, 0x83, 0x9f, 0xd3, 0x75, 0x08, 0xd2, 0x61, 0x73, 0x46, 0x72,
	0x68, 0x77, 0xb8, 0x71, 0xce, 0x31, 0xe7, 0xff, 0x60, 0xca, 0x21, 0xfc, 0xe2, 0xb7, 0x1f, 0xc9,
	0x58, 0xfe, 0xd9, 0xf9, 0xd3, 0x1b, 0x0f, 0x97, 0x46, 0x2d, 0x43, 0x37, 0xbb, 0x26, 0xd5, 0x54,
	0x36, 0x7a, 0xbd, 0xea, 0x6d, 0x53, 0x1e, 0x7f, 0x0e, 0x9f, 0x84, 0xbf, 0x57, 0x71, 0x7f, 0xe6,
	0xe8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xb5, 0x75, 0x87, 0x31, 0x05, 0x00, 0x00,
}
