version: "3.7"

x-base_go_service: &base_go_service
  image: golang
  volumes:
    - ${PWD}/../../:/go/src/ws
  working_dir: /go/src/ws

services:
  constructsserver:
    <<: *base_go_service
    command: go run ./example/gateway/constructsserver/main.go

  optionsserver:
    <<: *base_go_service
    command: go run ./example/gateway/optionsserver/main.go

  gateway:
    <<: *base_go_service
    command: go run ./cmd/gateway/main.go --config ./example/gateway/config.yaml
    ports:
    - 8080:8080
